sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t pankajbhomia/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true pankajbhomia/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket-name: "elasticbeanstalk-eu-west-2-728019983561"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

